import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
const dom = new JSDOM('', { url: 'http://localhost' });
globalThis.window = dom.window;
globalThis.localStorage = dom.window.localStorage;
const result = await build({ entryPoints: ['src/blueprints/service.ts'], bundle: true, write: false, format: 'esm', platform: 'browser' });
const service = await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const b = { uuid: '280f47b7-8434-410c-b854-380768fdccec', output_name: 'Test cannon', game_version: 'test-LIVE', ingredients: [], dismantle_returns: [], is_available_by_default: false, unlocking_missions_count: 0 };
assert.equal(service.materialQuantity({ quantity_scu: 0.36 }), '0.36 SCU');
assert.equal(service.materialQuantity({ quantity: 7 }), '7 item(s)');
assert.equal(service.materialQuantity({ quantity: 0 }), '0 item(s)');
assert.equal(service.materialQuantity({}), 'Quantity unknown');
assert.equal(service.acquisition(b), 'Acquisition unknown');
assert.match(service.normalizeBlueprint({ ...b, output_name: null, key: 'missing-item' }).output_name, /Unknown output/);
assert.equal(service.acquisition({ ...b, unlocking_missions_count: 1 }), 'Mission-linked');
let calls = 0;
window.fetch = async url => {
  calls++;
  if (calls === 2) assert.ok(url.includes('version=test-LIVE'));
  return { ok: true, json: async () => ({ data: [{ ...b, uuid: calls === 1 ? b.uuid : '280f47b7-8434-410c-b854-380768fdccea' }], meta: { last_page: 2 } }) };
};
assert.equal((await service.fetchBlueprints('', new AbortController().signal)).blueprints.length, 2);
assert.equal(calls, 2);
assert.equal(service.cachedBlueprints().version, 'test-LIVE');
window.fetch = async () => ({ ok: true, json: async () => ({ data: [{ ...b, game_version: 'wrong' }], meta: { last_page: 1 } }) });
await assert.rejects(service.fetchBlueprints('test-LIVE', new AbortController().signal), /version changed/);
assert.equal(service.cachedBlueprints().blueprints.length, 2);
window.fetch = async () => ({ ok: true, json: async () => ({ data: [b], meta: { last_page: 900 } }) });
await assert.rejects(service.fetchBlueprints('', new AbortController().signal), /pagination/);
window.fetch = async () => ({ ok: true, json: async () => ({ data: [{ uuid: 'bad' }], meta: { last_page: 1 } }) });
await assert.rejects(service.fetchBlueprints('', new AbortController().signal), /Invalid blueprint response/);
console.log('Blueprints: quantities, acquisition, pagination, version pinning, malformed data and cache preservation passed.');
